# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(171819)
$foreground = rgb(F2D5D3)
$color0 = rgb(3E3F40)
$color1 = rgb(18181A)
$color2 = rgb(41221F)
$color3 = rgb(503736)
$color4 = rgb(4B454A)
$color5 = rgb(875653)
$color6 = rgb(A36661)
$color7 = rgb(E4BBB8)
$color8 = rgb(9F8380)
$color9 = rgb(202022)
$color10 = rgb(572D2A)
$color11 = rgb(6A4948)
$color12 = rgb(645C63)
$color13 = rgb(B4736E)
$color14 = rgb(DA8881)
$color15 = rgb(E4BBB8)
