# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(2F2B2A)
$foreground = rgb(BFB6B6)
$color0 = rgb(464140)
$color1 = rgb(5A4D52)
$color2 = rgb(6A4628)
$color3 = rgb(323E6B)
$color4 = rgb(2D2A3C)
$color5 = rgb(292639)
$color6 = rgb(352323)
$color7 = rgb(9B8F8F)
$color8 = rgb(6C6464)
$color9 = rgb(78666E)
$color10 = rgb(8E5D36)
$color11 = rgb(42538F)
$color12 = rgb(3D384F)
$color13 = rgb(36334C)
$color14 = rgb(472F2F)
$color15 = rgb(9B8F8F)
